services:
  php-cli:
    build:
      context: ./docker/php-cli
    user: "${LOCAL_UID:-10001}:${LOCAL_GID:-10001}"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: ["sleep", "infinity"]
    tty: true
